# Generated by Django 5.0 on 2023-12-07 18:13

import django.core.validators
import registration_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_no', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000000), django.core.validators.MaxValueValidator(23999999), registration_form.models.validate_Student_digits])),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CSE(AIML)', 'CSE(AIML)'), ('CSE(DS)', 'CSE(DS)'), ('CSE(Hindi)', 'CSE(Hindi)'), ('AIML', 'AIML'), ('IT', 'IT'), ('CSIT', 'CSIT'), ('ECE', 'ECE'), ('EN', 'EN'), ('ME', 'ME'), ('CIVIL', 'CIVIL')], max_length=10)),
                ('email', models.EmailField(max_length=40, unique=True, validators=[registration_form.models.validate_akgec_email])),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999), registration_form.models.validate_Phone_digits])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15)),
                ('residence', models.CharField(choices=[('Hosteler', 'Hosteler'), ('Day scholar', 'Day scholar')], max_length=15)),
            ],
        ),
    ]
