# Generated by Django 5.0 on 2023-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='section',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4')]),
        ),
    ]
