# Generated by Django 5.0 on 2023-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0002_registration_section_alter_registration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=5),
        ),
    ]
